---
title: "20200619 Mobility"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(readxl)
library(tidyverse)
library(ggrepel)
setwd("~/Documents/GitHub/mobility")
```

# Importing data
```{r}
apple <- read_csv("applemobilitytrends-2020-06-27.csv") %>% filter(region == "India" | country == "India")
google <- read_csv("Google_Global_Mobility_Report.csv") %>% filter(country_region == "India")
```

## Reshape Apple data
```{r}
apple <- apple %>% pivot_longer(cols = c(7:length(apple)), names_to = "date")
apple$date <- as.Date(apple$date)
```

## Divide into national, state, and city
```{r}
apple_national <- apple %>% filter(region == "India")
apple_city <- apple %>% filter(region != "India")

google_national <- google %>% filter(is.na(sub_region_1))
google_state <- google %>% filter(!is.na(sub_region_1))
```

# Fetch COVID data 

## National
```{r}
national_cases <- read_csv("https://api.covid19india.org/csv/latest/case_time_series.csv")
national_cases$Date <- paste(national_cases$Date, " 2020")
national_cases$Date <- as.Date(national_cases$Date, "%d %B %Y")
```
## State level
```{r}
state_cases <- read_csv("https://api.covid19india.org/csv/latest/state_wise_daily.csv")
state_cases$Date <- as.Date(state_cases$Date, "%d-%b-%y")
state_cases <- pivot_longer(state_cases, cols = c(3:41) , names_to = "State")
state_cases <- pivot_wider(state_cases, id_cols = c(Date, State), names_from = "Status", values_from = "value")
```

## District level
```{r}
dist1 <- read_csv("https://api.covid19india.org/csv/latest/raw_data1.csv") %>% filter(`Detected State` == "Delhi" | `Detected District` == "Mumbai" | `Detected District` == "Pune" | `Detected District` == "Hyderabad" | `Detected District` == "Bengaluru Urban" | `Detected District` == "Chennai")
dist2 <- read_csv("https://api.covid19india.org/csv/latest/raw_data2.csv") %>% filter(`Detected State` == "Delhi" | `Detected District` == "Mumbai" | `Detected District` == "Pune" | `Detected District` == "Hyderabad" | `Detected District` == "Bengaluru Urban" | `Detected District` == "Chennai")
dist3 <- read_csv("https://api.covid19india.org/csv/latest/raw_data3.csv") %>% filter(`Detected State` == "Delhi" | `Detected District` == "Mumbai" | `Detected District` == "Pune" | `Detected District` == "Hyderabad" | `Detected District` == "Bengaluru Urban" | `Detected District` == "Chennai")
dist4 <- read_csv("https://api.covid19india.org/csv/latest/raw_data4.csv") %>% filter(`Detected State` == "Delhi" | `Detected District` == "Mumbai" | `Detected District` == "Pune" | `Detected District` == "Hyderabad" | `Detected District` == "Bengaluru Urban" | `Detected District` == "Chennai")
dist5 <- read_csv("https://api.covid19india.org/csv/latest/raw_data5.csv") %>% filter(`Detected State` == "Delhi" | `Detected District` == "Mumbai" | `Detected District` == "Pune" | `Detected District` == "Hyderabad" | `Detected District` == "Bengaluru Urban" | `Detected District` == "Chennai")
dist6 <- read_csv("https://api.covid19india.org/csv/latest/raw_data6.csv") %>% filter(`Detected State` == "Delhi" | `Detected District` == "Mumbai" | `Detected District` == "Pune" | `Detected District` == "Hyderabad" | `Detected District` == "Bengaluru Urban" | `Detected District` == "Chennai")
```

```{r}
raw1 <- rbind(dist1, dist2) %>% select(`Date Announced`, `Detected District`, `Detected State`, `Num cases`, `Current Status`)
raw2 <- rbind(dist3, dist4, dist5, dist6)  %>% select(`Date Announced`, `Detected District`, `Detected State`, `Num Cases`, `Current Status`)
names(raw1)[names(raw1) == "Num cases"] <- "Num Cases"

district_cases <- rbind(raw1, raw2)
```


```{r}
district_cases$`Detected District` <-  ifelse(district_cases$`Detected State` == "Delhi", "Delhi", district_cases$`Detected District`)
```

```{r}
remove(dist1, dist2, dist3, dist4, dist5, dist6, raw1, raw2)
```

## Collapse district data to daily values and reshape
```{r}
district_cases <- district_cases %>% group_by(`Detected District`, `Detected State`, `Date Announced`, `Current Status`) %>% summarize(value = sum(`Num Cases`))
district_cases$`Date Announced` <- as.Date(district_cases$`Date Announced`, "%d/%m/%Y")
district_cases <- pivot_wider(district_cases, id_cols = c(`Date Announced`, `Detected District`, `Detected State`), names_from = `Current Status`, values_from = value)
```

# Merge COVID data

## national
```{r}
final_national_google <- inner_join(google_national, national_cases, by = c("date" = "Date"))
final_national_google <- final_national_google %>% filter(date > "2020-03-20") %>% select(date, ends_with("baseline"), starts_with("Daily"))
names(final_national_google) <- c("Date", "Retail and Recreation", "Grocery and Pharmacy", "Parks", "Transit", "Workplaces", "Residential"    , "Daily Confirmed"    , "Daily Recovered"    , "Daily Deceased"    )

write_csv(final_national_google, "national_google.csv")
final_national_apple <- inner_join(apple_national, national_cases, by = c("date" = "Date"))
write_csv(final_national_apple, "national_apple.csv")
```

## state
```{r}
google_state$state <- substr(google_state$iso_3166_2_code, 4,5)
state <- inner_join(google_state, state_cases, by = c("date" = "Date", "state" = "State"))

names(state) 
state <- state %>% filter(date > "2020-03-20") %>% select(sub_region_1, date, ends_with("baseline"), starts_with("Daily"), Confirmed, Recovered, Deceased)

names(state) <- c("State", "Date", "Retail and Recreation", "Grocery and Pharmacy", "Parks", "Transit", "Workplaces", "Residential"    , "Confirmed"    , "Recovered"    , "Deceased"    )

state %>% select(State, Date, `Retail and Recreation`) %>% pivot_wider(names_from = State, values_from = `Retail and Recreation`) %>% write_csv("retail.csv")
state %>% select(State, Date, `Grocery and Pharmacy`) %>% pivot_wider(names_from = State, values_from = `Grocery and Pharmacy`) %>% write_csv("grocery.csv")
state %>% select(State, Date, `Parks`) %>% pivot_wider(names_from = State, values_from = `Parks`) %>% write_csv("parks.csv")
state %>% select(State, Date, `Transit`) %>% pivot_wider(names_from = State, values_from = `Transit`) %>% write_csv("transit.csv")
state %>% select(State, Date, `Workplaces`) %>% pivot_wider(names_from = State, values_from = `Workplaces`) %>% write_csv("workplaces.csv")
state %>% select(State, Date, `Residential`) %>% pivot_wider(names_from = State, values_from = `Residential`) %>% write_csv("residential.csv")
state %>% select(State, Date, `Confirmed`) %>% pivot_wider(names_from = State, values_from = `Confirmed`) %>% write_csv("state_cases.csv")

write_csv(state, "state.csv")
```

### pivot and write 6 files for the 6 kinds of data

## district
```{r}
apple_city <- pivot_wider(apple_city, id_cols = c(date, region), names_from = transportation_type, values_from = value)
district_cases$`Detected District` <- ifelse(district_cases$`Detected District` == "Bengaluru Urban", "Bangalore", district_cases$`Detected District`)
city <- inner_join(apple_city, district_cases, by = c("date" = "Date Announced", "region" = "Detected District"))

names(city)[names(city) == "Hospitalized"] = "Cases"
names(city)[names(city) == "driving"] = "Driving"
names(city)[names(city) == "walking"] = "Walking"

city <- city %>% filter(date > "2020-03-20")
write_csv(city, "city.csv")

city %>% filter(region == "Delhi") %>% write.csv("delhi.csv")
city %>% filter(region == "Mumbai") %>% write.csv("mumbai.csv")
city %>% filter(region == "Pune") %>% write.csv("pune.csv")
city %>% filter(region == "Bangalore") %>% write.csv("bangalore.csv")
city %>% filter(region == "Hyderabad") %>% write.csv("hyderabad.csv")
city %>% filter(region == "Chennai") %>% write.csv("chennai.csv")
```


